(defun append-lists(list1 list2)
	(if (null list1)
		list2
		(cons (first list1)(append-lists(rest list1) list2))
		)
	)

(print "Append two lists using examples (A B C) and (1 2 3)")
(terpri)
(print(append-lists '(A B C) '(1 2 3)))
(terpri)
(print "Test it with your own lists")
(terpri)
(print "Input a list (i.e. (x x x))")
(terpri)
(setq list1 (read))
(terpri)
(print "Input another list (i.e. (x x x))")
(terpri)
(setq list2 (read))
(terpri)
(print "Your list is ")
(print (append list1 list))